##########################################################################
## GAMBIT configuration for a next-to-minimal postprocessor (version 2) run
##
## Requires ExampleBit_A and ExampleBit_B
##
## Requires 'spartan.yaml' to be run first, as this will generate the
## data that we will postprocess.
##
##########################################################################


Parameters:
  # In this example we will simply be fitting the mean and standard deviation of a normal distribution.
  # Parameters to be read from the input data file need to have prior_type: none.
  NormalDist:
    mu:
      prior_type: none
    sigma:
      prior_type: none

  # These parameters don't exist in the original data file, but we
  # can still use them to satisfy dependencies because they have fixed values.
  #NUHM1:
  #  A0: 1
  #  M0: 2
  #  mH: 3
  #  M12: 4
  #  SignMu: 5
  #  TanBeta: 6

Priors:

  # None used

Printer:

  printer: hdf5
  options:
    output_file: "pp_results.hdf5"
    group: "/ppv2"
    delete_file_on_restart: true

  #printer: sqlite
  #options:
  #  output_file: "pp_results.sql"
  #  table_name: "ppv2"
  #  buffer_length: 100
  #  delete_file_on_restart: true


Scanner:

  use_scanner: postprocessor

  scanners:

    postprocessor:
      
      plugin: postprocessor
      
      # Usev1 of the postprocessor? The default version is v2.0.
      # version: "1.0" 

      # Turn off extra log output? (Won't be output unless using "debug: true" anyway, though.)
      # verbose_logging: false

      # Name of the new global likelihood contribution
      like: New_LogLike

      # Name of the combined new+old likelihood
      reweighted_like: Comb_LogLike

      # Add LogLike in the old output to New_LogLike in the new output
      add_to_like: [LogLike]

      # Allow overwriting of the old output with the new output (e.g. if you would rather name New_LogLike as LogLike)
      permit_discard_old_likes: false

      # Frequency to print status update message
      update_interval: 1000 

      # Number of points to distribute to worker processes each time they request more work      
      batch_size: 100 
      
      # Restrict postprocessing to points with LogLike > -1e99
      cut_greater_than: {"LogLike": -1e99} 

      # Restrict postprocessing to points with mu < 22
      cut_less_than: {"#NormalDist_parameters @NormalDist::primary_parameters::mu": 22} 

      # Throw away all points outside the above cuts
      discard_points_outside_cuts: true

      # Information about input dataset to be postprocessed
      reader:
        type: hdf5
        file: "runs/spartan/samples/gambit_output.hdf5"
        group: "/data"
        #reader:
        #  type: sqlite
        #  file: "runs/spartan/samples/results.sql"
        #  table: "spartan"


ObsLikes:

    # Test normal distribution likelihood
  - purpose:      New_LogLike
    capability:   normaldist_loglike
    module:       ExampleBit_A
    type:         double

    # Test activation of new fixed model parameters that
    # don't exist in the input file (this function requires
    # e.g. NUHM1 parameters to run)
    #- purpose:      New_LogLike
    #  capability:   Example_lnL_B
    #  type:         double
    #  function:     ""
    #  module:       ""

Rules:

  - capability: normaldist_loglike
    function: lnL_gaussian
    options:
       # Set sleep time between evaluations (in seconds)
       eval_time: 0.01

Logger:

  redirection:
    [Default]      : "default.log"
    [ExampleBit_A] : "ExampleBit_A.log"
    [Scanner]      : "Scanner.log"
    [Debug]        : "debug.log"
    [Scanner,Debug]: "Scanner_debug.log"

KeyValues:

  default_output_path: "runs/postprocessor_demo"

  rng:
    generator: ranlux48
    seed: -1

  print_timing_data: false

  debug: true

  likelihood:
    model_invalid_for_lnlike_below: -1e6
